
services:
  backend:
    build:
      context: .
    container_name: inmobiliaria-backend
    working_dir: /var/www
    volumes:
      - .:/var/www
    expose:
      - "8000"  # Solo lo expone a otros contenedores, no al host
    command: php artisan serve --host=0.0.0.0 --port=8000
    depends_on:
      - db

  webserver:
    image: nginx:alpine
    container_name: inmobiliaria-nginx
    ports:
      - "8000:80"  # expone el puerto 80 del contenedor como 8000 en tu PC
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: inmobiliaria-db
    environment:
      POSTGRES_DB: inmobiliaria
      POSTGRES_USER: inmobiliaria_user
      POSTGRES_PASSWORD: secret123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
